using System.ComponentModel;
using System.Data;
using System.Globalization;
using System.Security.Cryptography;
using System.Windows.Forms.VisualStyles;
using Syncfusion.XlsIO;
using Syncfusion.XlsIO.Implementation;
using Syncfusion.XlsIO.Implementation.PivotAnalysis;

namespace XLSIO_task;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();
        InitializeComponents();
    }
    private Button btnCreate;
    private Label label;
    private void InitializeComponents()
    {
        btnCreate = new Button();
        label = new Label();

        //Label
        label.Location = new System.Drawing.Point(0, 40);
        label.Size = new System.Drawing.Size(426, 35);
        label.Text = "Click the button to view an Excel spreadsheet generated by Essential XlsIO. Please note that MS Excel Viewer or MS Excel is required to view the resultant document.";
        label.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
        //Button
        btnCreate.Location = new System.Drawing.Point(180, 110);
        btnCreate.Size = new System.Drawing.Size(85, 26);
        btnCreate.Text = "Create Document";
        btnCreate.Click += new EventHandler(btnCreate_Click);

        //Create Spreadsheet
        ClientSize = new System.Drawing.Size(450, 150);
        Controls.Add(label);
        Controls.Add(btnCreate);
        Text = "Create Spreadsheet";

    }

    private void btnCreate_Click(object sender, EventArgs e)
    {
        using (ExcelEngine excelEngine = new ExcelEngine())
        {
            IApplication application = excelEngine.Excel;
            application.DefaultVersion = ExcelVersion.Xlsx;

            //Create a workbook
            IWorkbook workbook = application.Workbooks.Create(0);

            IWorksheet salesReportSheet = workbook.Worksheets.Create("Sales Report");
            IWorksheet dataSheet = workbook.Worksheets.Create("Data");

            PrepareDatasheet(dataSheet, workbook);
            PrepareReportSheet(dataSheet, salesReportSheet, workbook);
           
            workbook.SaveAs("task.xlsx");

            //Saving the workbook as stream
            // FileStream stream = new FileStream("task.xlsx", FileMode.Create, FileAccess.Write);
            // stream.Dispose();
        }
    }
}
